<?php
	require_once "auth.inc";
	require_once "time.inc";

	define("XK_HOME", "http://192.168.178.22/xtr-kartinatv/xKartina/");
	
	define("TEMPLATE", "rss-default");
	define("CATEGORY_TEMPLATE", "channel_list.xml");
	define("CHANNEL_ITEM_TEMPLATE", "channel_item.xml");
	
	define("CATEGORY_LIST_TEMPLATE", "category_list.xml");
	define("CATEGORY_ITEM_TEMPLATE", "category_item.xml");
	
	define("EPG_LIST_TEMPLATE", "epg_list.xml");
	define("EPG_ITEM_TEMPLATE", "epg_item.xml");
	
?>